"""add labor and parts matrices

Revision ID: b185cdf9e3a8
Revises: dcddda071505
Create Date: 2026-02-07 03:05:34.306779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b185cdf9e3a8'
down_revision = 'dcddda071505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labor_matrix_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('min_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_per_hour', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts_matrix_tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('min_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ro_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_ro_id'), ['ro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start_at'), ['start_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ro_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_ro_id'), ['ro_id'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address2', sa.String(length=255), nullable=True))

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_line_items_job_id'), ['job_id'], unique=False)
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_line_items_job_id'))
        batch_op.drop_column('job_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('address2')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_ro_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_start_at'))
        batch_op.drop_index(batch_op.f('ix_appointments_ro_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_end_at'))

    op.drop_table('appointments')
    op.drop_table('parts_matrix_tiers')
    op.drop_table('labor_matrix_tiers')
    # ### end Alembic commands ###
