"""initial

Revision ID: dcddda071505
Revises: 
Create Date: 2026-02-07 01:20:33.304097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcddda071505'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('engine', sa.String(length=80), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('odometer_last', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_make'), ['make'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vin'), ['vin'], unique=False)

    op.create_table('repair_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ro_number', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('concern', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repair_orders_ro_number'), ['ro_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_repair_orders_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ro_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ro_id', 'doc_type', 'version', name='uq_doc_ro_type_version')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_doc_ro_type_status', ['ro_id', 'doc_type', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_ro_id'), ['ro_id'], unique=False)

    op.create_table('ro_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ro_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ro_id'], ['repair_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ro_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ro_events_ro_id'), ['ro_id'], unique=False)

    op.create_table('line_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_items_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_items_document_id'))

    op.drop_table('line_items')
    with op.batch_alter_table('ro_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ro_events_ro_id'))

    op.drop_table('ro_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_ro_id'))
        batch_op.drop_index('ix_doc_ro_type_status')

    op.drop_table('documents')
    with op.batch_alter_table('repair_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_orders_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_repair_orders_ro_number'))
        batch_op.drop_index(batch_op.f('ix_repair_orders_customer_id'))

    op.drop_table('repair_orders')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicles_model'))
        batch_op.drop_index(batch_op.f('ix_vehicles_make'))
        batch_op.drop_index(batch_op.f('ix_vehicles_customer_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
